# Generated by Django 5.2.5 on 2025-09-01 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_type', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Converse', 'Converse'), ('Vans', 'Vans'), ('Reebok', 'Reebok'), ('Under Armour', 'Under Armour'), ('New Balance', 'New Balance'), ('Dr. Martens', 'Dr. Martens'), ('Jordan', 'Jordan'), ('Timberland', 'Timberland')], max_length=50)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
