# Generated by Django 5.2.5 on 2025-09-01 13:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
