# Generated by Django 5.2.5 on 2025-10-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0002_alter_sale_price_per_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shoe_type',
            field=models.CharField(choices=[('NIKE SHOX', 'NIKE SHOX'), ('TN AIRMAX', 'TN AIRMAX'), ('SB.DUNK', 'SB.DUNK'), ('PORTAL', 'PORTAL'), ('AIRMAX 95', 'AIRMAX 95'), ('JORDAN 1', 'JORDAN 1'), ('JORDAN 2', 'JORDAN 2'), ('JORDAN 3', 'JORDAN 3'), ('JORDAN 4', 'JORDAN 4'), ('JORDAN 5', 'JORDAN 5'), ('JORDAN 6', 'JORDAN 6'), ('JORDAN 11', 'JORDAN 11'), ('NIKE ZOOM', 'NIKE ZOOM'), ('AIRFORCE 1', 'AIRFORCE 1'), ('LUIS VUITTON', 'LUIS VUITTON'), ('ALEXANDER MC', 'ALEXANDER MC'), ('Dr. MARTENS', 'Dr. MARTENS'), ('CONVERSE TYLOR', 'CONVERSE TYLOR'), ('VANS KNU', 'VANS KNU'), ('ADDIDAS SAMBA', 'ADDIDAS SAMBA'), ('NB 530', 'NB 530'), ('NB 740', 'NB 740'), ('NB 760', 'NB 760'), ('NB 1906R', 'NB 1906R'), ('NB 9060 SEASALT', 'NB 9060 SEASALT'), ('TIMBERLAND', 'TIMBERLAND'), ('ADDIDAS CASUALS', 'ADDIDAS CASUALS'), ('REEBOK', 'REEBOK'), ('PUMA JOGGER', 'PUMA JOGGER'), ('PUMA PARKSTYLE', 'PUMA PARKSTYLE'), ('PUMA FENTY', 'PUMA FENTY'), ('PUMA SOFT-FOAM', 'PUMA SOFT-FOAM'), ('PUMA SUEDE', 'PUMA SUEDE'), ('CONVERSE LEATHER', 'CONVERSE LEATHER')], max_length=50),
        ),
    ]
