# Generated by Django 5.2.5 on 2025-10-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0003_alter_sale_shoe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/'),
        ),
    ]
