# Generated by Django 5.2.5 on 2025-10-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0004_sale_shoe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='shoe_image',
        ),
    ]
