# Generated by Django 5.2.5 on 2025-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0005_remove_sale_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
    ]
