# Generated by Django 5.2.5 on 2025-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0006_sale_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='picture',
        ),
        migrations.AddField(
            model_name='sale',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/'),
        ),
    ]
