# Generated by Django 5.2.7 on 2025-10-22 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellshoe', '0008_sale_user_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
