# Generated by Django 5.2.5 on 2025-09-01 13:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='pieces',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='shoe',
            constraint=models.UniqueConstraint(fields=('shoe_type', 'size', 'color'), name='uniq_shoe_sku'),
        ),
    ]
