# Generated by Django 5.2.5 on 2025-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_input', '0002_alter_shoe_buying_price_alter_shoe_pieces_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoe',
            name='uniq_shoe_sku',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='pieces',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(),
        ),
    ]
