# Generated by Django 5.2.5 on 2025-10-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_input', '0004_alter_shoe_shoe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
    ]
