# Generated by Django 6.0 on 2026-01-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_input', '0007_alter_shoe_shoe_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['shoe_type']},
        ),
    ]
