# Generated by Django 6.0 on 2026-01-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_input', '0008_alter_shoe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={},
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_type',
            field=models.CharField(choices=[('ADDIDAS CASUALS', 'ADDIDAS CASUALS'), ('ADDIDAS SAMBA', 'ADDIDAS SAMBA'), ('AIRFORCE 1', 'AIRFORCE 1'), ('AIRMAX 95', 'AIRMAX 95'), ('ALEXANDER MC', 'ALEXANDER MC'), ('CONVERSE TYLOR', 'CONVERSE TYLOR'), ('DR MARTEWS LOW CUT', 'DR MARTEWS LOW CUT'), ('JORDAN 1', 'JORDAN 1'), ('JORDAN 2', 'JORDAN 2'), ('JORDAN 3', 'JORDAN 3'), ('JORDAN 4', 'JORDAN 4'), ('JORDAN 5', 'JORDAN 5'), ('JORDAN 6', 'JORDAN 6'), ('JORDAN 11', 'JORDAN 11'), ('LUIS VUITTON', 'LUIS VUITTON'), ('NIKE FASTAGE', 'NIKE FASTAGE'), ('NIKE SHOX', 'NIKE SHOX'), ('NIKE VOMERO 5', 'NIKE VOMERO 5'), ('NIKE WORKOUT', 'NIKE WORKOUT'), ('NIKE ZOOM', 'NIKE ZOOM'), ('PUMA FENTY', 'PUMA FENTY'), ('PUMA JOGGER', 'PUMA JOGGER'), ('PUMA PARKSTYLE', 'PUMA PARKSTYLE'), ('PUMA SOFT-FOAM', 'PUMA SOFT-FOAM'), ('PUMA SUEDE', 'PUMA SUEDE'), ('PORTAL', 'PORTAL'), ('REEBOK', 'REEBOK'), ('SB.DUNK', 'SB.DUNK'), ('TIMBERLAND', 'TIMBERLAND'), ('TN AIRMAX', 'TN AIRMAX'), ('TRAVIS SCOTT J1 LOW CUT', 'TRAVIS SCOTT J1 LOW CUT'), ('VANS KNU', 'VANS KNU'), ('NB 1000', 'NB 1000'), ('NB 1906R', 'NB 1906R'), ('NB 530', 'NB 530'), ('NB 740', 'NB 740'), ('NB 760', 'NB 760'), ('NB 9060 SEASALT', 'NB 9060 SEASALT'), ('SB.DUNK', 'SB.DUNK')], max_length=50),
        ),
    ]
