# Generated by Django 6.0 on 2026-01-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_input', '0009_alter_shoe_options_alter_shoe_shoe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_type',
            field=models.CharField(choices=[('ADDIDAS CASUALS', 'ADDIDAS CASUALS'), ('ADDIDAS SAMBA', 'ADDIDAS SAMBA'), ('ALEXANDER MC', 'ALEXANDER MC'), ('AIRFORCE 1', 'AIRFORCE 1'), ('AIRMAX 95', 'AIRMAX 95'), ('CONVERSE TYLOR', 'CONVERSE TYLOR'), ('DR MARTEWS LOW CUT', 'DR MARTEWS LOW CUT'), ('Dr. MARTENS', 'Dr. MARTENS'), ('JORDAN 1', 'JORDAN 1'), ('JORDAN 11', 'JORDAN 11'), ('JORDAN 2', 'JORDAN 2'), ('JORDAN 3', 'JORDAN 3'), ('JORDAN 4', 'JORDAN 4'), ('JORDAN 5', 'JORDAN 5'), ('JORDAN 6', 'JORDAN 6'), ('LUIS VUITTON', 'LUIS VUITTON'), ('NB 1000', 'NB 1000'), ('NB 1906R', 'NB 1906R'), ('NB 530', 'NB 530'), ('NB 740', 'NB 740'), ('NB 760', 'NB 760'), ('NB 9060 SEASALT', 'NB 9060 SEASALT'), ('NIKE FASTAGE', 'NIKE FASTAGE'), ('NIKE SHOX', 'NIKE SHOX'), ('NIKE VOMERO 5', 'NIKE VOMERO 5'), ('NIKE WORKOUT', 'NIKE WORKOUT'), ('NIKE ZOOM', 'NIKE ZOOM'), ('PORTAL', 'PORTAL'), ('PUMA FENTY', 'PUMA FENTY'), ('PUMA JOGGER', 'PUMA JOGGER'), ('PUMA PARKSTYLE', 'PUMA PARKSTYLE'), ('PUMA SOFT-FOAM', 'PUMA SOFT-FOAM'), ('PUMA SUEDE', 'PUMA SUEDE'), ('REEBOK', 'REEBOK'), ('SB.DUNK', 'SB.DUNK'), ('TIMBERLAND', 'TIMBERLAND'), ('TN AIRMAX', 'TN AIRMAX'), ('TRAVIS SCOTT J1 LOW CUT', 'TRAVIS SCOTT J1 LOW CUT'), ('VANS KNU', 'VANS KNU')], max_length=50),
        ),
    ]
